// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQc3lnX10kVeUl4Z-hzccm7z9xDlej1yo',
    appId: '1:284462187575:web:bd9998a5f805af66e12bb2',
    messagingSenderId: '284462187575',
    projectId: 'fir-login-app-flutter',
    authDomain: 'fir-login-app-flutter.firebaseapp.com',
    storageBucket: 'fir-login-app-flutter.firebasestorage.app',
    measurementId: 'G-JDNN0N3KHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMQIXbW4NFu9Gx91LNpqDxV_N-3HDYBL0',
    appId: '1:284462187575:android:0f7fa7f414cf2c79e12bb2',
    messagingSenderId: '284462187575',
    projectId: 'fir-login-app-flutter',
    storageBucket: 'fir-login-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAiodogwixAGiiEmB8WD5OykjHM_3EGCU',
    appId: '1:284462187575:ios:333bc7848f97ed75e12bb2',
    messagingSenderId: '284462187575',
    projectId: 'fir-login-app-flutter',
    storageBucket: 'fir-login-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAiodogwixAGiiEmB8WD5OykjHM_3EGCU',
    appId: '1:284462187575:ios:333bc7848f97ed75e12bb2',
    messagingSenderId: '284462187575',
    projectId: 'fir-login-app-flutter',
    storageBucket: 'fir-login-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQc3lnX10kVeUl4Z-hzccm7z9xDlej1yo',
    appId: '1:284462187575:web:b98fb1c55792251be12bb2',
    messagingSenderId: '284462187575',
    projectId: 'fir-login-app-flutter',
    authDomain: 'fir-login-app-flutter.firebaseapp.com',
    storageBucket: 'fir-login-app-flutter.firebasestorage.app',
    measurementId: 'G-8X48PMB42H',
  );
}
